# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.18.2

# Mod Properties
mod_version=0.1.0-1.21.1-fabric
maven_group=com.sisariku.ciallomine
archives_base_name=ciallominedatapack

# Dependencies
fabric_api_version=0.116.9+1.21.1
fabric_kotlin_version=1.13.4+kotlin.2.2.0
kotlin_version=2.1.20
